spring:
    profiles:
        active: dev
---

spring:
    config:
        activate:
            on-profile: "dev"
    datasource:
        url: jdbc:postgresql://localhost:9876/cardapio-dev
        username: postgres
        password: admin
    jpa:
        properties:
            hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
    main:
        allow-bean-definition-overriding: true
    

    
---

# spring:
#     config:
#         activate:
#             on-profile: "prod"
#     datasource:
#         url: jdbc:postgresql://localhost:9876/departments
#         username: postgres
#         password: admin
#     jpa:
#         properties:
#             hibernate:
#             dialect: org.hibernate.dialect.PostgreSQLDialect
#         hibernate:
#             ddl-auto: update