spring:
    profiles:
        active: dev
---

spring:
    config:
        activate:
            on-profile: "dev"
    datasource:
        url: jdbc:postgresql://localhost:9876/departments-dev
        username: postgres
        password: admin
    jpa:
        properties:
            hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update

management:
    endpoints:
        web:
            exposure:
                include: "*"
                exclude: "env,beans"


---

spring:
    config:
        activate:
            on-profile: "prod"
    datasource:
        url: jdbc:postgresql://localhost:9876/departments
        username: postgres
        password: admin
    jpa:
        properties:
            hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update